### PR TITLE
fixed odd whitespace below the footer

### PR DESCRIPTION
**Pull request by vinitraj412**

### CODE REVIEW

**Comment by AdarshKumar712** [comment]
Could you please upload a screenshot of the changes you have made?

**Comment by vinitraj412** [comment]
there were similar whitespaces below the footer in all pages. I removed them.

**Comment by rakaar** [comment]
Hey @vinitraj412  
The white space is still in Contacts page and in announcement page 
Screenshot from 2019-12-12 18-19-16
Screenshot from 2019-12-12 18-19-22

**Comment by vinitraj412** [comment]
no there is no whitespace

**Comment by rakaar** [comment]
Hey @vinitraj412 ,  Resolve the conflicts update your currrent branch with the kwoc branch and push them so that the Pull Request gets updated and I will mege them

**Comment by rakaar** [comment]
Thanks @vinitraj412 , Great Job!

**Pull request merged**
