### PR TITLE
Change home sidebar CSS

### PR DESCRIPTION
**Pull request by leonardomaier**
PR created for issue #10

### CODE REVIEW

**Comment by leonardomaier** [comment]
@AdarshKumar712 check this out.

**Comment by AdarshKumar712** [comment]
Do upload a screenshot of the webpage

**Comment by leonardomaier** [comment]
Based on the reference you sent.

Any changes?

image

**Comment by leonardomaier** [comment]
@AdarshKumar712 I just saw that you have different menus between the pages. Maybe I could rename the CSS classes to make the style reusable between the pages before you merge this PR. I made this change specific for the home page and later I just realized that is not the same menu between pages.

**Comment by AdarshKumar712** [comment]
It's alright for now, once all the styles are finalized, then the changes will be applied to all the relevant pages

**Comment by AdarshKumar712** [comment]
Hey @leonardomaier, could you please set these change in CSS so that the change that you made apply to for all the relevant pages?

**Comment by leonardomaier** [comment]
@AdarshKumar712 sure, should I consider relevant pages as pages containing this type of menu? I will make the changes as soon as possible

**Comment by AdarshKumar712** [comment]
Yes, do consider all the relevant pages. I hope you are thinking to make the formatting a part of main.css so as make the changes to the respective class/id, such that the changes get applied to all the pages. Please do correct me if I am wrong.

**Comment by leonardomaier** [comment]
@AdarshKumar712 yes, that is exactly what I will do.

**Comment by leonardomaier** [comment]
@AdarshKumar712 I've made the changes.

**Comment by AdarshKumar712** [comment]
Could you please do the same for the Login.php as that page also contains the sidebar?
Btw Great work @leonardomaier!!!

**Comment by leonardomaier** [comment]
@AdarshKumar712 done!

**Comment by rakaar** [comment]
Hey @leonardomaier , Please resolve the conflicts, update your current branch with `kwoc` branch so that PR can be merged.

**Comment by leonardomaier** [comment]
@rakaar done!

**Pull request merged**
