### PR TITLE
Made changes in the design of Professors information page

### PR DESCRIPTION
**Pull request by Nishantgoyal918**
Made certain changes in the design of the Professor's information page. I am also attaching the screenshots. For Issue no #5 . Backend coding to get the professor's profile photo is left. 
Screenshot from 2019-12-12 02-23-47
Screenshot from 2019-12-12 02-24-00
Screenshot from 2019-12-12 02-24-05
Screenshot from 2019-12-12 02-24-16

### CODE REVIEW

**Comment by rakaar** [comment]
Hey  @Nishantgoyal918 
Great Job Done. The design is really good. Can you please look at these changes:
- Font style: The current font is a bit fancy, please replace it by a formal one. Like the one that suits best for a department website
- Search Results Not showing, Why is it not possible to fetch the search result of the professor.

**Comment by Nishantgoyal918** [comment]
I have made changes to the font style.
Screenshot from 2019-12-12 19-25-38
Is this font style fine and also what do you mean by 2nd issue? I don't get it. Can you please elaborate?

**Comment by rakaar** [comment]
@Nishantgoyal918 , Now it is nice. But I feel it will be better if you use the font used in the dropdown menu in the professor's information as well.

**Comment by Nishantgoyal918** [comment]
I have completed the backend coding for the profile photo of professors. I am attaching the screenshots for the same.
Screenshot from 2019-12-13 00-10-37
Screenshot from 2019-12-13 00-11-05

**Comment by rakaar** [comment]
Hey, @Nishantgoyal918 . Resolve the conflicts update your currrent branch with the `kwoc` branch and push them so that the Pull Request gets updated and I will mege them

**Comment by Nishantgoyal918** [comment]
I have resolved the conflicts.

**Comment by rakaar** [comment]
Thank you @Nishantgoyal918 . Great job with the design !
There is one small issue, Why is this thing weirdly below footer . Please remove it.
Screenshot from 2019-12-21 18-14-21

**Comment by rakaar** [comment]
Thanks @Nishantgoyal918 ! Great Job

**Pull request merged**
